---
# Copyright (c) 2020 The ARA Records Ansible authors
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

galaxy_info:
  author: The ARA Records Ansible authors
  description: Installs an ara-web javascript interface
  license: GPLv3
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 8
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - bionic
        - focal
  galaxy_tags:
    - ansible
    - ara
    - ara-web

dependencies: []
